version: '3.2'

services:
  mongodb:
    image: mongo:4.4.3
    restart: always
    networks:
      - warlock-network
  back-api:
    build: marvel-hero-navegator-backend/.
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src
    networks:
      - warlock-network
  front-api:
    build: marvel-hero-navegator-frontend/.
    ports:
      - '80:80'
    depends_on:
      - back-api
    restart: always
    volumes:
      - ./:/usr/src
    networks:
      - warlock-network
networks:
  warlock-network:
    driver: bridge